---
- name: Delete VMs from ESXi
  hosts: localhost
  gather_facts: false
  vars:
    esxi_hostname: "{{ lookup('env', 'ESXI_HOSTNAME') }}"
    esxi_username: "{{ lookup('env', 'ESXI_USERNAME') }}"
    esxi_password: "{{ lookup('env', 'ESXI_PASSWORD') }}"
    validate_certs: false

  tasks:
    - name: Delete VM esxi-1
      community.vmware.vmware_guest:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "vCLS-4c4c4544-004d-4810-8042-b1c04f463032"
        state: "absent"

    - name: Delete VM esxi-2
      community.vmware.vmware_guest:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "node1"
        state: "absent"
